#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME="${SERVICE_NAME:-remoteterminal}"
INSTALL_MODE="system"
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage: scripts/install_systemd_service.sh [--dry-run] [--user]

Options:
  --dry-run   Render local files and build artifacts, but do not call systemctl.
  --user      Install as a user service instead of a system service.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      ;;
    --user)
      INSTALL_MODE="user"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

APP_USER="${SUDO_USER:-${USER:-$(id -un)}}"
APP_HOME="$(getent passwd "$APP_USER" | cut -d: -f6)"
if [[ -z "$APP_HOME" ]]; then
  echo "failed to resolve home directory for $APP_USER" >&2
  exit 1
fi

APP_ROOT="$ROOT_DIR"
PROD_ROOT="${PROD_ROOT_OVERRIDE:-$APP_ROOT/.prod-runtime}"
PROD_CURRENT_DIR="$PROD_ROOT/current"
PROD_BIN_DIR="$PROD_CURRENT_DIR/bin"
PROD_FRONTEND_DIR="$PROD_CURRENT_DIR/frontend/dist"
PROD_CONFIG_DIR="$PROD_CURRENT_DIR/config"
PROD_VAR_DIR="$PROD_CURRENT_DIR/var"
PROD_DATA_DIR="$PROD_VAR_DIR/data"
PROD_LOG_DIR="$PROD_VAR_DIR/logs"
PROD_SCRIPTS_DIR="$PROD_CURRENT_DIR/scripts"
APP_DATA_DIR="$PROD_DATA_DIR"
APP_LOG_DIR="$PROD_LOG_DIR"
APP_ALLOWED_ROOT="${ALLOWED_ROOT_OVERRIDE:-$APP_HOME/code}"
APP_BIND_ADDR="${BIND_ADDR_OVERRIDE:-127.0.0.1:8080}"
APP_PUBLIC_BASE_URL="${PUBLIC_BASE_URL_OVERRIDE:-http://127.0.0.1:8080}"
APP_FRONTEND_DIST="$PROD_FRONTEND_DIR"
TTYD_INSTALL_ROOT="${TTYD_INSTALL_ROOT:-$APP_HOME/.local/opt/ttyd/pkg}"
CODEX_BIN_DIR=""

ENV_LOCAL="$PROD_CONFIG_DIR/remoteterminal.env"
UNIT_TEMPLATE="$APP_ROOT/deploy/systemd/remoteterminal.service.template"
UNIT_RENDERED="$APP_ROOT/deploy/systemd/${SERVICE_NAME}.service.rendered"
RUN_BACKEND_TEMPLATE="$APP_ROOT/deploy/runtime/run_backend.sh.template"
RUN_BACKEND_RENDERED="$PROD_SCRIPTS_DIR/run_backend.sh"

mkdir -p \
  "$APP_DATA_DIR" \
  "$APP_LOG_DIR" \
  "$PROD_BIN_DIR" \
  "$PROD_CONFIG_DIR" \
  "$PROD_FRONTEND_DIR" \
  "$PROD_SCRIPTS_DIR" \
  "$APP_ROOT/deploy/systemd"

export HOME="$APP_HOME"
export PATH="$APP_HOME/.local/bin:$PATH"

if [[ -f "$APP_HOME/.cargo/env" ]]; then
  # shellcheck disable=SC1090
  source "$APP_HOME/.cargo/env"
fi

if [[ -s "$APP_HOME/.nvm/nvm.sh" ]]; then
  # shellcheck disable=SC1090
  source "$APP_HOME/.nvm/nvm.sh"
  nvm use --silent default >/dev/null 2>&1 || true
fi

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  NVM_NODE_BIN="$(find "$APP_HOME/.nvm/versions/node" -mindepth 2 -maxdepth 2 -type d -name bin 2>/dev/null | sort | tail -n 1 || true)"
  if [[ -n "$NVM_NODE_BIN" ]]; then
    export PATH="$NVM_NODE_BIN:$PATH"
  fi
fi

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  echo "node and npm are required" >&2
  exit 1
fi

if command -v codex >/dev/null 2>&1; then
  CODEX_BIN_DIR="$(dirname "$(command -v codex)")"
fi

if ! command -v codex >/dev/null 2>&1; then
  echo "codex CLI is required and must already be installed" >&2
  exit 1
fi

if ! command -v dtach >/dev/null 2>&1; then
  echo "dtach is required; install it with your system package manager" >&2
  exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "cargo is required; install rustup first" >&2
  exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "cargo is still unavailable after sourcing rustup env" >&2
  exit 1
fi

if ! command -v ttyd >/dev/null 2>&1; then
  TARGET_HOME="$APP_HOME" TTYD_INSTALL_ROOT="$APP_HOME/.local/opt/ttyd" "$APP_ROOT/scripts/install_local_ttyd.sh"
fi

if [[ ! -d "$APP_ROOT/frontend/node_modules" ]]; then
  echo "[install] frontend dependencies"
  (
    cd "$APP_ROOT/frontend"
    npm ci
  )
fi

echo "[build] frontend dist"
"$APP_ROOT/scripts/build_frontend.sh"

echo "[publish] frontend dist -> $PROD_FRONTEND_DIR"
rm -rf "$PROD_FRONTEND_DIR"
mkdir -p "$PROD_FRONTEND_DIR"
cp -a "$APP_ROOT/frontend/dist/." "$PROD_FRONTEND_DIR/"

echo "[build] backend"
(
  cd "$APP_ROOT/backend"
  CARGO_TARGET_DIR="$APP_ROOT/backend/target-prod" cargo build --locked
)

install -m 0755 "$APP_ROOT/backend/target-prod/debug/backend" "$PROD_BIN_DIR/backend"

cat >"$ENV_LOCAL" <<EOF
# Generated by scripts/install_systemd_service.sh
HOME=$APP_HOME
BIND_ADDR=$APP_BIND_ADDR
DATA_DIR=$APP_DATA_DIR
ALLOWED_ROOT=$APP_ALLOWED_ROOT
PUBLIC_BASE_URL=$APP_PUBLIC_BASE_URL
FRONTEND_DIST=$APP_FRONTEND_DIST
TTYD_PORT_MIN=12000
TTYD_PORT_MAX=12999
TTYD_ROOT=$TTYD_INSTALL_ROOT
CODEX_BIN_DIR=$CODEX_BIN_DIR
RUST_LOG=info,sqlx=warn
EOF

sed \
  -e "s|__CURRENT_DIR__|$PROD_CURRENT_DIR|g" \
  -e "s|__ENV_FILE__|$ENV_LOCAL|g" \
  "$RUN_BACKEND_TEMPLATE" >"$RUN_BACKEND_RENDERED"
chmod 0755 "$RUN_BACKEND_RENDERED"

cat >"$PROD_CURRENT_DIR/RELEASE" <<EOF
published_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
source_repo=$APP_ROOT
backend_binary=$PROD_BIN_DIR/backend
frontend_dist=$PROD_FRONTEND_DIR
env_file=$ENV_LOCAL
EOF

if [[ $(id -u) -eq 0 ]]; then
  chown -R "$APP_USER:$APP_USER" "$PROD_ROOT"
fi

sed \
  -e "s|__APP_ROOT__|$APP_ROOT|g" \
  -e "s|__APP_USER__|$APP_USER|g" \
  -e "s|__APP_HOME__|$APP_HOME|g" \
  -e "s|__PROD_CURRENT_DIR__|$PROD_CURRENT_DIR|g" \
  -e "s|__PROD_ENV_FILE__|$ENV_LOCAL|g" \
  -e "s|__PROD_RUN_SCRIPT__|$RUN_BACKEND_RENDERED|g" \
  -e "s|__SERVICE_NAME__|$SERVICE_NAME|g" \
  "$UNIT_TEMPLATE" >"$UNIT_RENDERED"

if [[ "$INSTALL_MODE" == "user" ]]; then
  perl -0pi -e 's/WantedBy=multi-user\.target/WantedBy=default.target/' "$UNIT_RENDERED"
fi

echo "[rendered] $ENV_LOCAL"
echo "[rendered] $RUN_BACKEND_RENDERED"
echo "[rendered] $UNIT_RENDERED"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "[dry-run] skipped systemctl actions"
  exit 0
fi

if [[ "$INSTALL_MODE" == "user" ]]; then
  USER_UNIT_DIR="$APP_HOME/.config/systemd/user"
  mkdir -p "$USER_UNIT_DIR"
  install -m 0644 "$UNIT_RENDERED" "$USER_UNIT_DIR/$SERVICE_NAME.service"
  systemctl --user daemon-reload
  systemctl --user enable --now "$SERVICE_NAME.service"
  echo "[ok] user service installed: $SERVICE_NAME.service"
  exit 0
fi

if [[ $(id -u) -ne 0 ]]; then
  echo "system install needs root. Re-run with sudo:" >&2
  echo "  sudo SERVICE_NAME=$SERVICE_NAME $APP_ROOT/scripts/install_systemd_service.sh" >&2
  exit 1
fi

install -m 0644 "$UNIT_RENDERED" "/etc/systemd/system/$SERVICE_NAME.service"
systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME.service"

echo "[ok] system service installed: $SERVICE_NAME.service"
